# Generated by Django 5.1.1 on 2024-09-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_management', '0002_session_session_id_alter_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
