# Generated by Django 5.1.1 on 2024-09-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_management', '0006_session_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='participants',
        ),
        migrations.AddField(
            model_name='session',
            name='votes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
