# Generated by Django 5.1.1 on 2024-09-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='default-id', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
