# Generated by Django 5.1.1 on 2024-09-19 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_management', '0007_remove_session_participants_session_votes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
